# Process KPI
#
# To extract and reformat data ready to be filled in the excel template file.
#
# Gordon CHAN
#
# Aug 2015


# Set value for function development --------------------------------------

mock <- function(){
    require("xlsx")
    require("dplyr")
    require("lubridate")
    
    source("read_xlsx.R")
    
    Mmm<<-"May15"
    
}

mock()

# Helper function to help with reading source file ----------------------------------------

# i. Initialise empty dataframe for use by each measurements
#
# ii. Generate file table according to reporting month period specified

kpi_source_helper <- function(Mmm){
    
    require("xlsx")
    require("dplyr")
    
    if(!exists("read_range", mode="function")) source("read_xlsx.R")
    
    # Empty dataframe
    
    empty.frame <<- data.frame(CMC = numeric(0),
                              KCH = numeric(0),
                              KWH = numeric(0),
                              NLTH = numeric(0),
                              OLM = numeric(0),
                              PMH = numeric(0),
                              WTS = numeric(0),
                              YCH = numeric(0),
                              KWC = numeric(0),
                              HA = numeric(0))
    
    # File table
    # KPI targets
    
    target.kpi <<- data.frame(filename = c("targets.csv")) %>% mutate(filepath = file.path("target", Mmm, filename))
 
    
    # Clinical KPI

    source.kpi <- read.xlsx("source/KPI items.xlsx",
                            sheetName = "KPI",
                            colIndex = 4,
                            stringsAsFactors = FALSE)
    
    source.HA.kpi <- read.xlsx("source/KPI items.xlsx",
                            sheetName = "KPI",
                            colIndex = 5,
                            stringsAsFactors = FALSE)
            names(source.HA.kpi) <- "Query.Name"
    
    source.kpi <- bind_rows(source.kpi, source.HA.kpi)

        source.kpi <<- source.kpi %>% filter(!is.na(Query.Name)) %>%
            distinct(Query.Name) %>% arrange(Query.Name) %>%
            mutate(filename = paste(Query.Name, ".xlsx", sep = "")) %>%
            mutate(filepath = file.path("source", Mmm, filename))
    
    # KPI Trend
    source.tre <- read.xlsx("source/KPI items.xlsx",
                            sheetName = "KPI",
                            colIndex = 4,
                            stringsAsFactors = FALSE)
        
    source.HA.tre <- read.xlsx("source/KPI items.xlsx",
                            sheetName = "KPI",
                            colIndex = 5,
                            stringsAsFactors = FALSE)
        names(source.HA.tre) <- "Query.Name"
        
        source.tre <- bind_rows(source.tre, source.HA.tre)
        
        source.tre <<- source.tre %>% filter(!is.na(Query.Name)) %>%
            distinct(Query.Name) %>% arrange(Query.Name) %>%
            mutate(filename = paste(Query.Name, ".xlsx", sep = "")) %>%
            mutate(filepath = file.path("source", Mmm, filename))    
    
    # SOP KPI
    source.sop <- read.xlsx("source/KPI items.xlsx",
                            sheetName = "KPI",
                            colIndex = 4,
                            stringsAsFactors = FALSE)
        
    source.HA.sop <- read.xlsx("source/KPI items.xlsx",
                            sheetName = "KPI",
                            colIndex = 5,
                            stringsAsFactors = FALSE)
    names(source.HA.sop) <- "Query.Name"
        
        source.sop <- bind_rows(source.sop, source.HA.sop)
        
        source.sop <<- source.sop %>% filter(!is.na(Query.Name)) %>%
            distinct(Query.Name) %>% arrange(Query.Name) %>%
            mutate(filename = paste(Query.Name, ".xlsx", sep = "")) %>%
            mutate(filepath = file.path("source", Mmm, filename))    
}


# File name standardisation -----------------------------------------------

# To standardise filenames of files generated by different data sources



# KPI targets -------------------------------------------------------------

## * Need to convert to numeric where possible *
## * Need to calculate some items's target! *

# Return stored KPI targets according to the input kpi. s/n value
#
# Accept input of kpi. s/n (i.e. "kpi.1" to "kpi.7")

kpi.t <- function(i, Mmm){
    
    kpi_source_helper(Mmm)
    
    # KPI targets
    
    path <- target.kpi$filepath
    
    targets <- read.csv(path, stringsAsFactors = FALSE)
    
    rownames(targets) <- targets$KPI
    
    targets <- targets[,-1]
    
    # Filter KPI targets dataframe to return needed targets
    
    target.prod <- targets[i,]
    
    # Replace NA with N.A. for user in Excel
    
    target.prod <- lapply(target.prod, function(x){ifelse(is.na(x), "N.A.", x)})
        target.prod <- data.frame(target.prod)
    
    target.prod
}


# kpi.1 Access (A&E waiting time) ------------------------------------------------------

kpi.1 <- function(Mmm){
    
kpi_source_helper(Mmm)
    
    path <- grep("(.*kpi.1 .*)", source.kpi$filepath, value = TRUE)
    
    AE_WT <- read_range(path, 5:12, 1:14)
    
    AE_WT.frame <- empty.frame
    
    row.index <- c(2:5)
    
    for (i in 1:length(row.index)){
        AE_WT.frame[i,] <- rep(NA, length(AE_WT.frame))
    }
    
    # Fit processed data to dataframe and show NA data
    
    AE_WT <- AE_WT[row.index,]
    
    # row.names(AE_WT.frame) <- row.names(AE_WT)
    
    for (i in 1:length(AE_WT.frame)){
        if (names(AE_WT.frame)[i] %in% names(AE_WT)){
            AE_WT.frame[i] <- AE_WT[names(AE_WT.frame)[i]]
        }
    }
    
    
    # Replace NA with N.A. for production use in Excel
    
    AE_WT.prod <- as.matrix(AE_WT.frame, rownames.force = TRUE)
    AE_WT.prod <- apply(AE_WT.prod, 2, FUN = function(x){ifelse(is.na(x), "N.A.", x)})
    
    AE_WT.prod <- data.frame(
        lapply(split(AE_WT.prod, col(AE_WT.prod)), type.convert, as.is = TRUE),
        stringsAsFactors = FALSE
    )
    row.names(AE_WT.prod) <- row.names(AE_WT.frame)
    names(AE_WT.prod) <- names(AE_WT.frame)
    
    for (i in 1:length(AE_WT.prod)){
        AE_WT.prod[,i] <- sapply(AE_WT.prod[,i], FUN = function(x) ifelse(is.numeric(x), x/100, x))
    }
    
    # Return production ready dataframe
    
    AE_WT.prod
}

# kpi.2 Access(SOP waiting time) ------------------------------------------

kpi.2 <- function(Mmm, specialty = "Ovr"){
    
    kpi_source_helper(Mmm)
    
#     SOP.specialty <- data.frame(
#         specialty = c("ENT" , "GYN" , "MED" , "OPH" , "ORT" , "PAE" , "PSY" , "SUR"),
#         specialty.df = paste("SOP_WT.", SOP.specialty, sep = ""))
    
    path <- grep("(.*kpi.2 .*)", source.kpi$filepath, value = TRUE)
    path.HA <- grep("(.*kpi.2.HA .*)", source.kpi$filepath, value = TRUE)
    
    SOP_WT <- read_range(path, 5:28, 1:55)
    SOP_WT.HA <- read_range(path.HA, 5:28, 1:10)
        row.index <- c(3:4, 10, 14, 20)

    SOP_WT.frame <- empty.frame
    
            for (i in 1:length(row.index)){
                SOP_WT.frame[i,] <- rep(NA, length(SOP_WT.frame))
            }
    
    # Split data into dataframes per specialty and show NA data
    
    SOP_WT <- SOP_WT[row.index,]
    SOP_WT.HA <- SOP_WT.HA[row.index,]
    
    colnames(SOP_WT) <- gsub("( Mgt)", "", colnames(SOP_WT))
    colnames(SOP_WT.HA) <- gsub("( Inst.$)", "", colnames(SOP_WT.HA))
    
    for (i in 1:(length(SOP_WT)-1)){
        SOP_WT[,i+1] <- as.numeric(SOP_WT[,i+1])
    }
    
    for (i in 1:(length(SOP_WT.HA)-1)){
        SOP_WT.HA[,i+1] <- as.numeric(SOP_WT.HA[,i+1])
    }
    
    
    if (specialty=="ENT"){
            SOP_WT.Spl <- cbind(SOP_WT[,c(1,2:6)], SOP_WT.HA[,c(2,1)])
    } else if (specialty=="GYN"){
            SOP_WT.Spl <- cbind(SOP_WT[,c(1,7:12)], SOP_WT.HA[,c(3,1)]) 
    } else if (specialty=="MED"){
            SOP_WT.Spl <- cbind(SOP_WT[,c(1,13:19)], SOP_WT.HA[,c(4,1)])
    } else if (specialty=="OPH"){
            SOP_WT.Spl <- cbind(SOP_WT[,c(1,20:23)], SOP_WT.HA[,c(5,1)])
    } else if (specialty=="ORT"){
            SOP_WT.Spl <- cbind(SOP_WT[,c(1,24:30)], SOP_WT.HA[,c(6,1)])
    } else if (specialty=="PAE"){
            SOP_WT.Spl <- cbind(SOP_WT[,c(1,31:46)], SOP_WT.HA[,c(7,1)])
    } else if (specialty=="PSY"){
            SOP_WT.Spl <- cbind(SOP_WT[,c(1,37:40)], SOP_WT.HA[,c(8,1)])
    } else if (specialty=="SUR"){
            SOP_WT.Spl <- cbind(SOP_WT[,c(1,41:47)], SOP_WT.HA[,c(9,1)])
    } else if (specialty=="Ovr"){
            SOP_WT.Spl <- cbind(SOP_WT[,c(1,48:55)], SOP_WT.HA[,c(10,1)])
    }


    for (i in 1:length(SOP_WT.frame)){
        if (names(SOP_WT.frame)[i] %in% names(SOP_WT.Spl)){
            SOP_WT.frame[i] <- SOP_WT.Spl[names(SOP_WT.frame)[i]]
        }
    }
    
    # Convert percentage into decimals
    
    percent_row <- c(3:4)
    
    for (i in 1:length(percent_row)){
            SOP_WT.frame[percent_row[i],] <- sapply(SOP_WT.frame[percent_row[i],], FUN = function(x) ifelse(is.numeric(x), x/100, x))
    }
    
    # Replace NA with N.A. for production use in Excel
    
    SOP_WT.prod <- data.frame(apply(SOP_WT.frame, 2, FUN = function(x){ifelse(is.na(x), "N.A.", x)}), stringsAsFactors = FALSE)
    
    for (i in 1:ncol(SOP_WT.prod)){
        if ("N.A." %in% SOP_WT.prod[,i]){
        } else {
                SOP_WT.prod[,i] <- as.numeric(SOP_WT.prod[,i])
        }
    }
    
    # Return production ready dataframe
    
    SOP_WT.prod
    
}


# kpi.5 Efficiency --------------------------------------------------------

kpi.5 <- function(kpi, Mmm){
    
    kpi_source_helper(Mmm)
    
    path <- grep("(.*kpi.5 .*)", source.kpi$filepath, value = TRUE)
    
    Bed.occ <- read_range(path, 6:20, 1:17)
    Bed.alos <- read_range(path, 6:20, c(1,18:32))
        row.index <- c(13)
    
    Bed.frame <- empty.frame
        for (i in 1:(length(row.index)*2)){
            Bed.frame[i,] <- rep(NA, length(Bed.frame))
        }
    
    # Convert to numeric class
        
        for (i in 1:(ncol(Bed.occ)-1)){
            Bed.occ[,i+1] <- as.numeric(Bed.occ[,i+1])
        }
    
        for (i in 1:(ncol(Bed.alos)-1)){
            Bed.alos[,i+1] <- as.numeric(Bed.alos[,i+1])
        }
    
    # Conver IP bed occupancy rate to decimal percentage
        
        for (i in 1:ncol(Bed.occ)){
            Bed.occ[,i] <- sapply(Bed.occ[,i], FUN = function(x){ifelse(is.numeric(x), x/100, x)})
        }
    
    # Subset dataframes with row_index
    
    Bed.occ <- Bed.occ[row.index,]
    Bed.alos <- Bed.alos[row.index,]
    
    # Combine Occ & ALOS as single dataframe
        
    for (i in 1:ncol(Bed.frame)){
        if (names(Bed.frame)[i] %in% names(Bed.occ)){
            Bed.frame[1,i] <- Bed.occ[names(Bed.frame)[i]]
            }
        }
        
    for (i in 1:ncol(Bed.frame)){
        if (names(Bed.frame)[i] %in% names(Bed.alos)){
            Bed.frame[2,i] <- Bed.alos[names(Bed.frame)[i]]
            }
        }
    
    # Select Occ or ALOS data
    
    
    if (kpi=="kpi.5.2"){
        Bed.frame <- Bed.frame[1,]
    } else if (kpi=="kpi.5.3"){
        Bed.frame <- Bed.frame[2,]
    }
    
    # Replace NA with N.A. for use in Excel

    Bed.prod <- lapply(Bed.frame, function(x){ifelse(is.na(x), "N.A.", x)})
        Bed.prod <- data.frame(Bed.prod)
    
    # Return production dataframe
    
    Bed.prod
    
}
    

# kpi.3.4 & 10 Quality - Unplanned Readmission Rate within 28 days for g --------

kpi.10 <- function(Mnn, show_specialty = FALSE){
    
    kpi_source_helper(Mmm)
    
    path <- grep("(.*kpi.10 .*)", source.kpi$filepath, value = TRUE)
    
    URR <- read_range(path, 5:26, 1:15)
    
    for (i in 1:(ncol(URR)-1)){
        URR[,i+1] <- as.numeric(URR[,i+1])
    }
    
    # Check if return need to be shown by specialty and subset accordingly
    
        if (show_specialty == FALSE){
            
            URR.frame <- empty.frame
                URR.frame[1,] <- NA
            
            row.index <- 20
            URR <- URR[row.index,]
            
            for (i in 1:length(URR.frame)){
                if (names(URR.frame)[i] %in% names(URR)){
                    URR.frame[i] <- URR[names(URR.frame)[i]]
                }
            }

        } else {
            URR.frame <- URR
        }

    # Convert to decimal percentage *(Need to consider if requried for show_specialty=TRUE)*
    
    for (i in 1:ncol(URR.frame)){
            URR.frame[,i] <- sapply(URR.frame[,i], FUN = function(x){ifelse(is.numeric(x), x/100, x)})
    }
    
    # Replace NA with N.A. for use in Excel
    
    if (nrow(URR.frame)>1){
        URR.prod <- data.frame(apply(URR.frame, 2, FUN = function(x){ifelse(is.na(x), "N.A.", x)}), stringsAsFactors = FALSE)
    } else if (nrow(URR.frame)==1){
        URR.prod <- lapply(URR.frame, function(x){ifelse(is.na(x), "N.A.", x)})
        URR.prod <-data.frame(URR.prod)
    }
    
    
#     for (i in 1:ncol(URR.prod)){
#         if ("N.A." %in% URR.prod[,i]){
#         } else {
#             URR.prod[,i] <- as.numeric(URR.prod[,i])
#         }
#     }
    
    # Return production ready dataframe
    
    URR.prod
}
