# Process KPI
#
# To extract and reformat data ready to be filled in the excel template file.
#
# Gordon CHAN
#
# Aug 2015


# Set value for function development --------------------------------------

# mock <- function(){
#     require("xlsx")
#     require("dplyr")
#     require("lubridate")
#     
#     source("read_xlsx.R")
#     
#     Mmm <<- "May15"
#     
#     path <<- file.path("source", Mmm, "kpi.4.1 Stroke.xlsx")
#     
# }
# 
# mock()

# Helper function to help with reading source file ----------------------------------------

# i. Initialise empty dataframe for use by each measurements
#
# ii. Generate file table according to reporting month period specified

kpi_source_helper <- function(Mmm){
    
    require("xlsx")
    require("dplyr")
    
    if(!exists("read_range", mode="function")) source("read_xlsx.R")
    if(!exists("read_html", mode="function")) source("read_html.R")
    
    # Empty dataframe
    
    empty.frame <<- data.frame(CMC = numeric(0),
                              KCH = numeric(0),
                              KWH = numeric(0),
                              NLTH = numeric(0),
                              OLM = numeric(0),
                              PMH = numeric(0),
                              WTS = numeric(0),
                              YCH = numeric(0),
                              KWC = numeric(0),
                              HA = numeric(0))
    
    # File table
    # KPI targets
    
    target.kpi <<- data.frame(filename = c("targets.csv")) %>%
        mutate(filepath = file.path("target", Mmm, filename))
 
    
    # Clinical KPI

    source.HA.kpi <- read.xlsx("source/KPI items.xlsx",
                            sheetName = "KPI",
                            colIndex = 5,
                            stringsAsFactors = FALSE)
            names(source.HA.kpi) <- "Query.Name"

        source.kpi <<- data.frame(filename = list.files(file.path("source", Mmm), pattern = ".*\\.xls.?")) %>%
            mutate(filepath = file.path("source", Mmm, filename))
    
    # KPI Trend
    source.tre <- read.xlsx("source/KPI items.xlsx",
                            sheetName = "KPI",
                            colIndex = 4,
                            stringsAsFactors = FALSE)
        
    source.HA.tre <- read.xlsx("source/KPI items.xlsx",
                            sheetName = "KPI",
                            colIndex = 5,
                            stringsAsFactors = FALSE)
        names(source.HA.tre) <- "Query.Name"
        
        source.tre <- bind_rows(source.tre, source.HA.tre)
        
        source.tre <<- source.tre %>% filter(!is.na(Query.Name)) %>%
            distinct(Query.Name) %>% arrange(Query.Name) %>%
            mutate(filename = paste(Query.Name, ".xlsx", sep = "")) %>%
            mutate(filepath = file.path("source", Mmm, filename))    
    
    # SOP KPI
    source.sop <- read.xlsx("source/KPI items.xlsx",
                            sheetName = "KPI",
                            colIndex = 4,
                            stringsAsFactors = FALSE)
        
    source.HA.sop <- read.xlsx("source/KPI items.xlsx",
                            sheetName = "KPI",
                            colIndex = 5,
                            stringsAsFactors = FALSE)
    names(source.HA.sop) <- "Query.Name"
        
        source.sop <- bind_rows(source.sop, source.HA.sop)
        
        source.sop <<- source.sop %>% filter(!is.na(Query.Name)) %>%
            distinct(Query.Name) %>% arrange(Query.Name) %>%
            mutate(filename = paste(Query.Name, ".xlsx", sep = "")) %>%
            mutate(filepath = file.path("source", Mmm, filename))    
}

# File name standardisation -----------------------------------------------

# To standardise filenames of files generated by different data sources

file.std <- function(Mmm){
    
    require("dplyr")
    
    path <- file.path("source",Mmm)
    
    if (file.exists(file.path(path, "CDARS"))){ ## Check if "CDARS" folder exist
        # File table of original and standardised filenames
        ori.cdars <- data.frame(ori.name = list.files(file.path(path, "CDARS"))) %>%
            mutate(std.name = gsub("(^[0-9]*_)", "", ori.name)) %>%
            mutate(std.name = gsub("(_)", " ", std.name)) %>%
            mutate(std.name = gsub("([[:alnum:]])([0-9])", "\\1.\\2", std.name)) %>%
            mutate(std.name = gsub("([0-9])([0-9])", "\\1.\\2", std.name))
        # Copy kpi files with standardised names
        for (i in 1:nrow(ori.cdars)){
            file.copy(from = file.path(path, "CDARS", ori.cdars$ori.name[i]),
                      to = file.path(path, "CDARD", ori.cdars$std.name[i]))
        }
    }
    
    if (file.exists(file.path(path, "MIPO"))){ ## Check if "MIPO" folder exist
        ori.mipo <- data.frame(list.files(file.path(path, "MIPO")))
        
        ## TO BE COMPLETED PENDING MIPO FILES ON SERVER ##
    }
}

# KPI targets -------------------------------------------------------------

## * Need to convert to numeric where possible *
## * Need to calculate some items's target! *

# Return stored KPI targets according to the input kpi. s/n value
#
# Accept input of kpi. s/n (i.e. "kpi.1" to "kpi.7")

kpi.t <- function(i, Mmm){
    
    kpi_source_helper(Mmm)
    
    # KPI targets
    
    path <- target.kpi$filepath
    
    targets <- read.csv(path, stringsAsFactors = FALSE)
    
    rownames(targets) <- targets$KPI
    
    targets <- targets[,-1]
    
    # Filter KPI targets dataframe to return needed targets
    
    target.prod <- targets[i,]
    
    # Replace NA with N.A. for user in Excel
    
    target.prod <- lapply(target.prod, function(x){ifelse(is.na(x), "N.A.", x)})
        target.prod <- data.frame(target.prod)
    
    target.prod
}


# kpi.1 Access (A&E waiting time) ------------------------------------------------------

kpi.1 <- function(Mmm){
    
kpi_source_helper(Mmm)
    
    path <- grep("(.*kpi.1 .*)", source.kpi$filepath, value = TRUE)
    
    AE_WT <- read_range(path, 5:12, 1:14)
    
    AE_WT.frame <- empty.frame
    
    row.index <- c(2:5)
    
    for (i in 1:length(row.index)){
        AE_WT.frame[i,] <- rep(NA, length(AE_WT.frame))
    }
    
    # Fit processed data to dataframe and show NA data
    
    AE_WT <- AE_WT[row.index,]

    
    for (i in 1:length(AE_WT.frame)){
        if (names(AE_WT.frame)[i] %in% names(AE_WT)){
            AE_WT.frame[i] <- AE_WT[names(AE_WT.frame)[i]]
        }
    }
    
    
    # Replace NA with N.A. for production use in Excel
    
    AE_WT.prod <- as.matrix(AE_WT.frame, rownames.force = TRUE)
    AE_WT.prod <- apply(AE_WT.prod, 2, FUN = function(x){ifelse(is.na(x), "N.A.", x)})
    
    AE_WT.prod <- data.frame(
        lapply(split(AE_WT.prod, col(AE_WT.prod)), type.convert, as.is = TRUE),
        stringsAsFactors = FALSE
    )
    row.names(AE_WT.prod) <- row.names(AE_WT.frame)
    names(AE_WT.prod) <- names(AE_WT.frame)
    
    for (i in 1:length(AE_WT.prod)){
        AE_WT.prod[,i] <- sapply(AE_WT.prod[,i], FUN = function(x) ifelse(is.numeric(x), x/100, x))
    }
    
    # Return production ready dataframe
    
    AE_WT.prod
}

# kpi.2 Access(SOP waiting time) ------------------------------------------

kpi.2 <- function(Mmm, specialty = "Overall", index = 1:5){
    
    kpi_source_helper(Mmm)
    
    path <- grep("(.*kpi.2 .*)", source.kpi$filepath, value = TRUE)
    path.HA <- grep("(.*kpi.2.HA .*)", source.kpi$filepath, value = TRUE)
    
    SOP_WT <- fuzzy_range(path, 5:32, 1:60)
    SOP_WT.HA <- fuzzy_range(path.HA, 5:32, 1:10)
    
    # Screen relevant rows
    row.break <- grep("   SOP$", SOP_WT.HA[,1])
    
    row.index <- numeric(0)
    
    row.data1 <- which(as.numeric(row.names(SOP_WT.HA)) > row.break[1] & as.numeric(row.names(SOP_WT.HA)) < row.break[2]-1)
    row.data2 <- which(as.numeric(row.names(SOP_WT.HA)) > row.break[2] & as.numeric(row.names(SOP_WT.HA)) < row.break[3]-1)
    row.data3 <- which(as.numeric(row.names(SOP_WT.HA)) > row.break[3] & as.numeric(row.names(SOP_WT.HA)) < row.break[4]-1)
    row.data4 <- which(as.numeric(row.names(SOP_WT.HA)) > row.break[4])
    
    row.index[1] <- which(grepl(".*Tri P1$", SOP_WT.HA[row.data1, 1])) + row.break[1]
    row.index[2] <- which(grepl(".*Tri P2$", SOP_WT.HA[row.data1, 1])) + row.break[1]
    row.index[3] <- which(grepl(".*Tri P1$", SOP_WT.HA[row.data2, 1])) + row.break[2]
    row.index[4] <- which(grepl(".*Tri P2$", SOP_WT.HA[row.data3, 1])) + row.break[3]
    row.index[5] <- which(grepl(".*Tri R$", SOP_WT.HA[row.data4, 1])) + row.break[4]
    
    
    SOP_WT.frame <- empty.frame
    
    for (i in 1:length(row.index)){
        SOP_WT.frame[i,] <- rep(NA, length(SOP_WT.frame))
    }
    
    # Split data into dataframes per specialty and show NA data
    
    col.start <- which(SOP_WT[1,] == specialty)
    specialty.index <- which(!is.na(SOP_WT[1,]))
    col.end <- if(specialty=="Overall"){
        ncol(SOP_WT)
    }else{
        specialty.index[which(specialty.index == col.start) + 1]
    }
    col.HA <- which(SOP_WT.HA[1,] == specialty)
    
    SOP_WT[2,] <- gsub("( Mgt)", "", SOP_WT[2,])
    SOP_WT.HA[2,] <- gsub("( Inst.$)", "", SOP_WT.HA[2,])
    
    SOP_WT.Spl <- cbind.data.frame(SOP_WT[,c(col.start:col.end)], SOP_WT.HA[,c(col.HA)], stringsAsFactors = FALSE)
    
    SOP_WT.Spl[2, which(SOP_WT.Spl[2,]=="Overall")] <- "KWC"
    colnames(SOP_WT.Spl) <- SOP_WT.Spl[2,]
    
    SOP_WT.Spl <- SOP_WT.Spl[row.index,]
    
    
    for (i in 1:(length(SOP_WT.Spl))){
        SOP_WT.Spl[,i] <- as.numeric(SOP_WT.Spl[,i])
    }
    
    for (i in 1:length(SOP_WT.frame)){
        if (names(SOP_WT.frame)[i] %in% names(SOP_WT.Spl)){
            SOP_WT.frame[i] <- SOP_WT.Spl[names(SOP_WT.frame)[i]]
        }
    }
    
    # Convert percentage into decimals
    
    percent_row <- c(3:4)
    
    for (i in 1:length(percent_row)){
        SOP_WT.frame[percent_row[i],] <- sapply(SOP_WT.frame[percent_row[i],], FUN = function(x) ifelse(is.numeric(x), x/100, x))
    }
    
    # Replace NA with N.A. for production use in Excel
    
    SOP_WT.prod <- data.frame(apply(SOP_WT.frame, 2, FUN = function(x){ifelse(is.na(x), "N.A.", x)}), stringsAsFactors = FALSE)
    
    for (i in 1:ncol(SOP_WT.prod)){
        if ("N.A." %in% SOP_WT.prod[,i]){
        } else {
            SOP_WT.prod[,i] <- as.numeric(SOP_WT.prod[,i])
        }
    }
    
    # If SOP WT for 1st priority is 0, replace as <1
    
    # SOP_WT.prod[1,] <- gsub("^0.*", "<1", SOP_WT.prod[1,])
    
    # Return production ready dataframe
    
    SOP_WT.prod <- SOP_WT.prod[index,]
    
    SOP_WT.prod
    
}


# kpi.3 Quality ----------------------------------------------------------
kpi.3 <- function(kpi, Mmm){
    
    kpi_source_helper(Mmm)
    
    SAR.frame <- empty.frame
    SAR.frame[1,] <- NA
    
    if(kpi=="kpi.3.1"){
        path.1st <- grep("(.*kpi.3.1.1 .*)", source.kpi$filepath, value = TRUE)
        path.adm <- grep("(.*kpi.3.1.2 .*)", source.kpi$filepath, value = TRUE)
        
        SAR.1st <- fuzzy_range(path.1st, 67:240, 1:22)
        SAR.adm <- fuzzy_range(path.adm, 116:290, 1:22)
        
        for (i in 1:4){
            SAR.1st[1,i] <- SAR.1st[2,i]
            SAR.adm[1,i] <- SAR.adm[2,i]
        }
        
        names(SAR.1st) <- SAR.1st[1,]
        names(SAR.adm) <- SAR.adm[1,]
        
        SAR.1st <- SAR.1st[-c(1:2),]
        SAR.adm <- SAR.adm[-c(1:2),]
        
    }else if(kpi=="kpi.3.2"){
        path.1st <- grep("(.*kpi.3.2.1 .*)", source.kpi$filepath, value = TRUE)
        path.adm <- grep("(.*kpi.3.2.2 .*)", source.kpi$filepath, value = TRUE)
        
        SAR.1st <- fuzzy_range(path.1st, 71:210, 1:22)
        SAR.adm <- fuzzy_range(path.adm, 120:250, 1:22)
        
        for (i in 1:4){
            SAR.1st[1,i] <- SAR.1st[2,i]
            SAR.adm[1,i] <- SAR.adm[2,i]
        }
        
        names(SAR.1st) <- SAR.1st[1,]
        names(SAR.adm) <- SAR.adm[1,]
        
        SAR.1st <- SAR.1st[-c(1:2),]
        SAR.adm <- SAR.adm[-c(1:2),]
        
    }
    
    names(SAR.1st) <- gsub("(Row Total)", "HA", names(SAR.1st))
    names(SAR.adm) <- gsub("(Row Total)", "HA", names(SAR.adm))
    
    names(SAR.1st) <- gsub("( \\(.*\\))", "", names(SAR.1st))
    names(SAR.adm) <- gsub("( \\(.*\\))", "", names(SAR.adm))
    
    names(SAR.1st) <- gsub("( $)", "", names(SAR.1st))
    names(SAR.adm) <- gsub("( $)", "", names(SAR.adm))
    
    names(SAR.1st) <- gsub("( )", "_", names(SAR.1st))
    names(SAR.adm) <- gsub("( )", "_", names(SAR.adm))
    
    for (i in 1:(22-4)){
        SAR.1st[,i+4] <- as.numeric(SAR.1st[,i+4])
        SAR.adm[,i+4] <- as.numeric(SAR.adm[,i+4])
    }
    
    # Substitute NA with 0
    
    SAR.1st[is.na(SAR.1st)] <- 0 
    SAR.adm[is.na(SAR.adm)] <- 0
    
    # Select KWC hospitals & HA
    
    SAR.1st <- SAR.1st %>% filter(!grepl("Total", Admission_Age)) %>%
        mutate(KWC = CMC + KWH + NLTH + PMH + YCH) %>%
        select(Admission_Age, Sex, Ambulance_Case, Triage_Category, CMC.1 = CMC, KWH.1 = KWH, NLTH.1 = NLTH, PMH.1 = PMH, YCH.1 = YCH, KWC.1 = KWC, HA.1 = HA)
    
    SAR.adm <- SAR.adm %>% filter(!grepl("Total", Admission_Age)) %>%
        mutate(KWC = CMC + KWH + NLTH + PMH + YCH) %>%
        select(Admission_Age, Sex, Ambulance_Case, Triage_Category, CMC.a = CMC, KWH.a = KWH, NLTH.a = NLTH, PMH.a = PMH, YCH.a = YCH, KWC.a = KWC, HA.a = HA)
    
    SAR <- suppressMessages(full_join(SAR.1st, SAR.adm))
    
    for (i in 1:(ncol(SAR)-4)){
        SAR[,i+4] <- sapply(SAR[,i+4], FUN = function(x){ifelse(is.na(x), 0, x)})
    }
    
    SAR.req <- SAR %>% select(-Admission_Age, -Sex, -Ambulance_Case, -Triage_Category) %>% mutate(HA = HA.a/HA.1) %>%
        mutate(CMC = CMC.1 * HA, KWH = KWH.1 * HA,  NLTH = NLTH.1 * HA, PMH = PMH.1 * HA, YCH = YCH.1 * HA, KWC = KWC.1 * HA) %>%
        summarise_each(funs(sum))
    
    SAR.frame$HA <- SAR.req$HA.a/SAR.req$HA.1
    SAR.frame$CMC <- SAR.req$CMC.a/SAR.req$CMC*SAR.frame$HA
    SAR.frame$KWH <- SAR.req$KWH.a/SAR.req$KWH*SAR.frame$HA
    SAR.frame$NLTH <- SAR.req$NLTH.a/SAR.req$NLTH*SAR.frame$HA
    SAR.frame$PMH <- SAR.req$PMH.a/SAR.req$PMH*SAR.frame$HA
    SAR.frame$YCH <- SAR.req$YCH.a/SAR.req$YCH*SAR.frame$HA
    SAR.frame$KWC <- SAR.req$KWC.a/SAR.req$KWC*SAR.frame$HA
    
    # Replace NA with N.A. for use in Excel
    
    SAR.prod <- data.frame(lapply(SAR.frame, FUN = function(x){ifelse(is.na(x), "N.A.", x)}), stringsAsFactors = FALSE)
    
    for (i in 1:ncol(SAR.prod)){
        if ("N.A." %in% SAR.prod[,i]){
        } else {
            SAR.prod[,i] <- as.numeric(SAR.prod[,i])
        }
    }
    
    SAR.prod
    
}

kpi.3.3 <- function(Mmm, trend = FALSE, row){
    
    require("tidyr")
    
    kpi_source_helper(Mmm)
    
    path <- grep("(.*kpi.3.3 .*)", source.kpi$filepath, value = TRUE)
    
    MRSA.frame <- empty.frame
    
    MRSA <- fuzzy_range(path, 12:470, 1:8)
    
    names(MRSA) <- MRSA[1,]
    MRSA <- MRSA[-1,] %>% select(Period, Hospital, contains("acute"))
    
    names(MRSA) <- gsub("(^No. of )", "", names(MRSA))
    names(MRSA) <- gsub("(^.*/.*$)", "per_1000_PD", names(MRSA))
    names(MRSA) <- gsub("( )", "_", names(MRSA))
    names(MRSA) <- gsub("(_Bacteremia)", "", names(MRSA))
    
    
    for (i in 1:3){
        MRSA[,i+2] <- as.numeric(MRSA[,i+2])
    }
    
    MRSA <- MRSA %>% mutate(per_1000_PD = MRSA_in_Acute_Beds/Acute_Patient_Days*1000)
    
    MRSA.HA <- MRSA %>% group_by(Period) %>%
        summarise(Hospital = "HA", MRSA_in_Acute_Beds = sum(MRSA_in_Acute_Beds), Acute_Patient_Days = sum(Acute_Patient_Days)) %>%
        mutate(per_1000_PD = MRSA_in_Acute_Beds/Acute_Patient_Days*1000)
    
    MRSA <- MRSA %>% filter(Hospital %in% c(names(MRSA.frame), "NLT")) %>% arrange(Period, Hospital)
    
    MRSA.KWC <- MRSA %>% group_by(Period) %>%
        summarise(Hospital = "KWC", MRSA_in_Acute_Beds = sum(MRSA_in_Acute_Beds), Acute_Patient_Days = sum(Acute_Patient_Days)) %>%
        mutate(per_1000_PD = MRSA_in_Acute_Beds/Acute_Patient_Days*1000)
    
    MRSA <- bind_rows(MRSA, MRSA.KWC, MRSA.HA)
    
    if(trend==TRUE){
        
        MRSA.req <- MRSA %>% select(-MRSA_in_Acute_Beds, -Acute_Patient_Days) %>% spread(key = Period, value = per_1000_PD)
        
        MRSA.KWC.req <- MRSA.req %>% filter(Hospital=="KWC")
        MRSA.HA.req <- MRSA.req %>% filter(Hospital=="HA")
        MRSA.req <- MRSA.req %>% filter(Hospital!="HA" & Hospital!="KWC") #%>%
            #filter(Hospital!="KCH" & Hospital!="WTS")
        
        
        MRSA.req <- bind_rows(MRSA.req, MRSA.KWC.req, MRSA.HA.req)
        
        rownames(MRSA.req) <- MRSA.req$Hospital
        
        MRSA.req <- MRSA.req %>% select(-Hospital)
        
        # Replace NA with ""
        
        MRSA.req[is.na(MRSA.req)] <- ""
        
        MRSA.prod <- MRSA.req
        
    }else{
        
        MRSA.req <- MRSA %>% ungroup() %>% group_by(Hospital) %>%
            summarise(MRSA_in_Acute_Beds = sum(MRSA_in_Acute_Beds), Acute_Patient_Days = sum(Acute_Patient_Days)) %>%
            mutate(per_1000_PD = MRSA_in_Acute_Beds/Acute_Patient_Days*1000) %>%
            select(-MRSA_in_Acute_Beds, -Acute_Patient_Days) %>%
            t() %>% as.data.frame(stringsAsFactors=FALSE)
        
        names(MRSA.req) <- MRSA.req[1,]
        MRSA.req <- MRSA.req[-1,]
        
        # Fill empty frame
        
        names(MRSA.req) <- gsub("NLT", "NLTH", names(MRSA.req))
        
        MRSA.frame[1,] <- NA
        
        for (i in 1:length(MRSA.frame)){
            if (names(MRSA.frame)[i] %in% names(MRSA.req)){
                MRSA.frame[i] <- MRSA.req[names(MRSA.frame)[i]]
            }
        }
        
        # Replace NA with N.A. for Excel use
        
        MRSA.prod <- data.frame(lapply(MRSA.frame, FUN = function(x){ifelse(is.na(x), "N.A.", x)}), stringsAsFactors = FALSE)
        
        for (i in 1:ncol(MRSA.prod)){
            if ("N.A." %in% MRSA.prod[,i]){
            } else {
                MRSA.prod[,i] <- as.numeric(MRSA.prod[,i])
            }
        }
        
    }
    
    # Return production ready dataframe
    
    MRSA.prod
}

# kpi.4 Disease specific Quality Indicator --------------------------------

#
# Used fuzzy_range to cater for variable number of rows
#

kpi.4.1 <- function(Mmm){
    
kpi_source_helper(Mmm)
    
    path <- grep("(.*kpi.4.1 .*)", source.kpi$filepath, value = TRUE)

    Stroke.frame <- empty.frame
    Stroke.frame[1,] <- NA
    
    
    Stroke <- fuzzy_range(path, 138:170, 1:5)
    
        names(Stroke) <- c("cluster", "institution", "ASU", "other", "total")
    
        Stroke$institution <- gsub("^Subtotal.*", "Subtotal", Stroke$institution)
        
        Stroke <- Stroke[-c(1:2),] %>% filter(cluster == "KW" | institution == "Subtotal" | is.na(institution))
    
        Stroke[nrow(Stroke),1] <- "HA"
        
    Stroke$institution <- gsub(".*total.*", NA, Stroke$institution)
    
    Stroke$cluster <- gsub(" $", "", Stroke$cluster)
    Stroke$cluster <- sapply(Stroke$cluster, FUN = function(x){ifelse(x=="HA", x, paste(x,"C", sep = ""))})
    
    for (i in 1:nrow(Stroke)){
        if (is.na(Stroke$institution[i])){
            Stroke$institution[i] <- Stroke$cluster[i]
        }
        if (is.na(Stroke$ASU[i]) & Stroke$other[i]!=0){
            Stroke$ASU[i] <- 0
        }
    }
    
    for (i in 1:3){
        Stroke[,i+2] <- as.numeric(Stroke[,i+2])
    }
    
    Stroke <- Stroke %>% mutate(ASU.rate = ASU/total) %>%
        select(institution, ASU.rate) %>%
        t() %>% as.data.frame(stringsAsFactors = FALSE)
    
    names(Stroke) <- Stroke[1,]
    
    Stroke <- Stroke[-1,]
    
    Stroke <- data.frame(lapply(Stroke[1,], FUN = function(x) as.numeric(x)))
    
        
    for (i in 1:length(Stroke.frame)){
        if (names(Stroke.frame)[i] %in% names(Stroke)){
            Stroke.frame[i] <- Stroke[names(Stroke.frame)[i]]
        }
    }
    
    # Replace NA with N.A. for use in Excel
    
    Stroke.prod <- lapply(Stroke.frame, function(x){ifelse(is.na(x), "N.A.", x)})
    Stroke.prod <- data.frame(Stroke.prod)
    
    # Return production dataframe

    Stroke.prod
    
}

kpi.4.2 <- function(Mmm){
    
    kpi_source_helper(Mmm)
    
    path <- grep("(.*kpi.4.2 .*)", source.kpi$filepath, value = TRUE)
    
    Hip.frame <- empty.frame
        Hip.frame[1,] <- NA
    
    
    Hip <- fuzzy_range(path, 84:110, 1:6)
    
    names(Hip) <- c("cluster", "institution", "within_2", "between_2_to_4", "other", "total")
    
    Hip$institution <- gsub("^Subtotal.*", "Subtotal", Hip$institution)
    
    Hip <- Hip[-c(1:2),] %>% filter(cluster == "KW" | institution == "Subtotal" | is.na(institution))
    
    Hip[nrow(Hip),1] <- "HA"
    
    Hip$institution <- gsub(".*total.*", NA, Hip$institution)
    
    Hip$cluster <- gsub(" $", "", Hip$cluster)
    Hip$cluster <- sapply(Hip$cluster, FUN = function(x){ifelse(x=="HA", x, paste(x,"C", sep = ""))})
    
    for (i in 1:nrow(Hip)){
        if (is.na(Hip$institution[i])){
            Hip$institution[i] <- Hip$cluster[i]
        }
        if (is.na(Hip$within_2[i]) & Hip$between_2_to_4[i]!=0){
            Hip$within.2[i] <- 0
        }
    }
    
    for (i in 1:4){
        Hip[,i+2] <- as.numeric(Hip[,i+2])
    }
    
    Hip <- Hip %>% mutate(within_2.rate = within_2/total) %>%
        select(institution, within_2.rate) %>%
        t() %>% as.data.frame(stringsAsFactors = FALSE)
    
    names(Hip) <- Hip[1,]
    
    Hip <- Hip[-1,]
    
    Hip <- data.frame(lapply(Hip[1,], FUN = function(x) as.numeric(x)))
    
    
    for (i in 1:length(Hip.frame)){
        if (names(Hip.frame)[i] %in% names(Hip)){
            Hip.frame[i] <- Hip[names(Hip.frame)[i]]
        }
    }
    
    # Replace NA with N.A. for use in Excel
    
    Hip.prod <- lapply(Hip.frame, function(x){ifelse(is.na(x), "N.A.", x)})
    Hip.prod <- data.frame(Hip.prod)
    
    # Return production dataframe
    
    Hip.prod
    
}

kpi.4.3 <- function(Mmm){
    
    kpi_source_helper(Mmm)
    
    path <- grep("(.*kpi.4.3 .*)", source.kpi$filepath, value = TRUE)
    
    AMI.frame <- empty.frame
    AMI.frame[1,] <- NA
    
    AMI <- raw_range(path, 36:44, 1:2)
    AMI.HA <- raw_range(path, 36:43, 10:11)
    
    names(AMI) <- AMI[1,]
        AMI <- AMI[-1,]
    names(AMI.HA) <- AMI.HA[1,]
        AMI.HA <- AMI.HA[-1,]
        
    AMI <- AMI %>% t() %>% as.data.frame(stringsAsFactors = FALSE)
    AMI.HA <- AMI.HA %>% t() %>% as.data.frame(stringsAsFactors = FALSE)
    
    AMI <- cbind(AMI, AMI.HA)
    
    names(AMI) <- AMI[1,]

    AMI <- AMI[-1,]

    names(AMI)[which(names(AMI)=="NLT")] <- "NLTH"
    
    AMI <- data.frame(lapply(AMI[1,], FUN = function(x){as.numeric(x)}))
    AMI <- data.frame(lapply(AMI[1,], FUN = function(x){x/100}))
    
    for (i in 1:length(AMI.frame)){
        if (names(AMI.frame)[i] %in% names(AMI)){
            AMI.frame[i] <- AMI[names(AMI.frame)[i]]
        }
    }
    
    # Replace NA with N.A. for use in Excel
    
    AMI.prod <- lapply(AMI.frame, function(x){ifelse(is.na(x), "N.A.", x)})
    AMI.prod <- data.frame(AMI.prod)
    
    # Return production dataframe
    
    AMI.prod
}

# kpi.5 Efficiency --------------------------------------------------------

kpi.5.1 <- function(Mmm){
    
    kpi_source_helper(Mmm)
    
    path <- grep("(.*kpi.8 .*)", source.kpi$filepath, value = TRUE)
    
    DS_SDS.frame <- empty.frame
        DS_SDS.frame[1,] <- NA
        
    DS_SDS <- fuzzy_range(path, 118:220, 1:6)
    
    names(DS_SDS) <- c("cluster", "institution", "specialty", "total", "DS", "SDS")
    
    DS_SDS$institution <- gsub("^Subtotal.*", "Subtotal", DS_SDS$institution)
    
    DS_SDS <- DS_SDS[-c(1),] %>% filter(cluster == "KW" | institution == "Subtotal" | is.na(institution))
    
    DS_SDS[nrow(DS_SDS),1] <- "HA"
    
    DS_SDS$institution <- gsub(".*total.*", NA, DS_SDS$institution)
    
    DS_SDS$cluster <- gsub(" $", "", DS_SDS$cluster)
    DS_SDS$cluster <- sapply(DS_SDS$cluster, FUN = function(x){ifelse(x=="HA", x, paste(x,"C", sep = ""))})
    
    
    for (i in 1:nrow(DS_SDS)){
            if (is.na(DS_SDS$institution[i])){
                DS_SDS$institution[i] <- DS_SDS$cluster[i]
                }
            if (is.na(DS_SDS$DS[i]) & DS_SDS$total[i]!=0){
                DS_SDS$DS[i] <- 0
                }
            if (is.na(DS_SDS$SDS[i]) & DS_SDS$total[i]!=0){
                DS_SDS$SDS[i] <- 0
                }
        }
    
    for (i in 1:3){
        DS_SDS[,i+3] <- as.numeric(DS_SDS[,i+3])
    }
    
    
    DS_SDS <- DS_SDS %>% filter(cluster=="KWC" | cluster=="HA") %>% 
        group_by(institution) %>% summarise(DS = sum(DS), SDS = sum(SDS), total = sum(total))
    
    DS_SDS <- DS_SDS %>% mutate(DS_SDS = DS + SDS) %>%
        mutate(DS_SDS.rate = DS_SDS/total) %>%
        select(institution, DS_SDS.rate) %>%
        t() %>% as.data.frame(stringsAsFactors = FALSE)
    
    names(DS_SDS) <- DS_SDS[1,]
    
    DS_SDS <- DS_SDS[-1,]
    
    DS_SDS <- data.frame(lapply(DS_SDS[1,], FUN = function(x) as.numeric(x)))
    
    
    for (i in 1:length(DS_SDS.frame)){
        if (names(DS_SDS.frame)[i] %in% names(DS_SDS)){
            DS_SDS.frame[i] <- DS_SDS[names(DS_SDS.frame)[i]]
        }
    }
    
    # Replace NA with N.A. for use in Excel
    
    DS_SDS.prod <- lapply(DS_SDS.frame, function(x){ifelse(is.na(x), "N.A.", x)})
    DS_SDS.prod <- data.frame(DS_SDS.prod)
    
    # Return production dataframe
    
    DS_SDS.prod
}

kpi.5 <- function(kpi, Mmm){
    
    kpi_source_helper(Mmm)
    
    path <- grep("(.*kpi.5 .*)", source.kpi$filepath, value = TRUE)
    
    Bed.occ <- read_range(path, 6:20, 1:17)
    Bed.alos <- read_range(path, 6:20, c(1,18:32))
        row.index <- c(13)
    
    Bed.frame <- empty.frame
        for (i in 1:(length(row.index)*2)){
            Bed.frame[i,] <- rep(NA, length(Bed.frame))
        }
    
    # Convert to numeric class
        
        for (i in 1:(ncol(Bed.occ)-1)){
            Bed.occ[,i+1] <- as.numeric(Bed.occ[,i+1])
        }
    
        for (i in 1:(ncol(Bed.alos)-1)){
            Bed.alos[,i+1] <- as.numeric(Bed.alos[,i+1])
        }
    
    # Conver IP bed occupancy rate to decimal percentage
        
        for (i in 1:ncol(Bed.occ)){
            Bed.occ[,i] <- sapply(Bed.occ[,i], FUN = function(x){ifelse(is.numeric(x), x/100, x)})
        }
    
    # Subset dataframes with row_index
    
    Bed.occ <- Bed.occ[row.index,]
    Bed.alos <- Bed.alos[row.index,]
    
    # Combine Occ & ALOS as single dataframe
        
    for (i in 1:ncol(Bed.frame)){
        if (names(Bed.frame)[i] %in% names(Bed.occ)){
            Bed.frame[1,i] <- Bed.occ[names(Bed.frame)[i]]
            }
        }
        
    for (i in 1:ncol(Bed.frame)){
        if (names(Bed.frame)[i] %in% names(Bed.alos)){
            Bed.frame[2,i] <- Bed.alos[names(Bed.frame)[i]]
            }
        }
    
    # Select Occ or ALOS data
    
    
    if (kpi=="kpi.5.2"){
        Bed.frame <- Bed.frame[1,]
    } else if (kpi=="kpi.5.3"){
        Bed.frame <- Bed.frame[2,]
    }
    
    # Replace NA with N.A. for use in Excel

    Bed.prod <- lapply(Bed.frame, function(x){ifelse(is.na(x), "N.A.", x)})
        Bed.prod <- data.frame(Bed.prod)
    
    # Return production dataframe
    
    Bed.prod
    
}
    

# kpi.6 Waiting time for elective Total Joint Replacement -----------------

kpi.6 <- function(kpi, Mmm){
    
    require("dplyr")
    
    kpi_source_helper(Mmm)

        regex <- "(.*kpi.6 .*)"
        regex.HA <- "(.*kpi.6.HA .*)"
        

    path <- grep(regex, source.kpi$filepath, value = TRUE)
    path.HA <- grep(regex.HA, source.kpi$filepath, value = TRUE)
    
    TJR.frame <- empty.frame
    TJR.frame[1,] <- NA
    
    TJR <- fuzzy_range(path, 10:26, 1:5, 2)
    TJR.HA <- raw_range(path.HA, 10:26, 1:5, 2)
    
    TJR[,1] <- gsub("( [0-9]{2})", "", TJR[,1])
    TJR.HA[,1] <- gsub("( [0-9]{2})", "", TJR.HA[,1])
    
    names(TJR) <- TJR[1,]
    names(TJR.HA) <- TJR.HA[1,]
    
    TJR <- TJR[-1,]
    TJR$Institution <- gsub("(^ )", "", TJR$Institution)
    
    TJR.HA$Institution <- gsub("( Overall$)", "", TJR.HA$Institution)
    TJR.HA$Institution <- gsub("(^ )", "", TJR.HA$Institution)
    
    TJR.HA <- TJR.HA %>% filter(Institution=="HA")

    TJR <- bind_rows(TJR, TJR.HA) %>% arrange(Period)
    
    names(TJR) <- c("Period", "Institution", "percentile.90", "Case_Performed", "Notional")
    
    TJR$Case_Performed <- gsub(",", "", TJR$Case_Performed)
    
    # Select period column
    
    Mmm.regex <- paste("(- ", Mmm, "$)", sep = "")
    
    TJR <- TJR %>% filter(grepl(Mmm.regex, Period))
    
    # Select 90 percentile OR notional Waiting Time
    
    if (kpi=="kpi.6.1"){
        
        TJR.req <- TJR %>% select(Institution, percentile.90) %>%
            t() %>% as.data.frame(stringsAsFactors=FALSE)
        
    } else if (kpi=="kpi.6.2"){
        
        TJR.req <- TJR %>% select(Institution, Notional) %>%
            t() %>% as.data.frame(stringsAsFactors=FALSE)
        
    }
    
    # Reformat
    
    names(TJR.req) <- TJR.req[1,]
    
    TJR.req <- TJR.req[-1,]

    TJR.req <- data.frame(lapply(TJR.req[1,], FUN = function(x) as.numeric(x)))

    for (i in 1:ncol(TJR.frame)){
        if (names(TJR.frame)[i] %in% names(TJR.req)){
            TJR.frame[i] <- TJR.req[names(TJR.frame)[i]]
        }
    }
    
    # Replace NA with N.A. for use in Excel
    
    TJR.prod <- lapply(TJR.frame, function(x){ifelse(is.na(x), "N.A.", x)})
    TJR.prod <- data.frame(TJR.prod)
    
    # Return production dataframe
    
    TJR.prod
 
}


# kpi.7 Waiting Time for diagnostic radiological investigations -----------

kpi.7 <- function(kpi, Mmm){
    
    kpi_source_helper(Mmm)
    
    path <- grep("(.*kpi.7 .*)", source.kpi$filepath, value = TRUE)
    
    RAD <- raw_range(path, 1:113, 1:11)
    
    RAD.frame <- empty.frame
    RAD.frame[1,] <- NA
    
    # Cleaning variable names and datatype
    
    RAD[1,] <- gsub("(^[0-9]{2})", "p.\\1", RAD[1,])
    RAD[1,] <- gsub("( pcntile)", "", RAD[1,])
    RAD[1,] <- gsub("(. waiting time)", "", RAD[1,])
    RAD[1,] <- gsub("(Type)", "H24_case", RAD[1,])
    
    names(RAD) <- RAD[1,]
    RAD <- RAD[-1,]
    
    
    for (i in 1:5){
        RAD[,i+6] <- suppressWarnings(as.numeric(RAD[,i+6]))
    }
    
    RAD$Period <- gsub("( [0-9]{2})", "", RAD$Period)
    RAD$Hospital <- gsub("( Average$)", "", RAD$Hospital)
    
    RAD <- RAD %>% filter(grepl("^Including ", H24_case))
    
    # Select columns
    
    RAD.req <- RAD %>% select(Period, Hospital, Modality, p.90)
    
    # Filter period
    
    Mmm.regex <- paste("(- ", Mmm, "$)", sep = "")
    
    RAD.req <- RAD.req %>% filter(grepl(Mmm.regex, Period))
    
    # Filter required Modality
    
    if (kpi=="kpi.7.1"){
        RAD.req <- RAD.req %>% filter(Modality=="CT")
    } else if (kpi=="kpi.7.2"){
        RAD.req <- RAD.req %>% filter(Modality=="MRI")
    } else if (kpi=="kpi.7.3"){
        RAD.req <- RAD.req %>% filter(Modality=="US")
    } else if (kpi=="kpi.7.4"){
        RAD.req <- RAD.req %>% filter(Modality=="MAMMO")
    }
    
    # Simplify to required columns
    
    RAD.req <- RAD.req %>% select(Hospital, p.90) %>%
        t() %>% as.data.frame(stringsAsFactors=FALSE)
    
    
    # Reformat
    
    names(RAD.req) <- RAD.req[1,]
    RAD.req <- RAD.req[-1,]
    
    names(RAD.req) <- gsub(" *$", "", names(RAD.req))
    
    RAD.req <- data.frame(lapply(RAD.req[1,], FUN = function(x) as.numeric(x)))
    
    for (i in 1:ncol(RAD.frame)){
        if (names(RAD.frame)[i] %in% names(RAD.req)){
            RAD.frame[i] <- RAD.req[names(RAD.frame)[i]]
        }
    }
    
    # Replace NA with N.A. for use in Excel
    
    RAD.prod <- lapply(RAD.frame, function(x){ifelse(is.na(x), "N.A.", x)})
    RAD.prod <- data.frame(RAD.prod)
    
    # Return production dataframe
    
    RAD.prod
}

# kpi.8 Rate of Day Surgery plus Same Day Surgery for different specialty -----------

kpi.8 <- function(Mmm, spec = "Overall", inst = "KWC"){
    
    # Check input
    
    specialty.list <- c("Overall",
                        "ENT",
                        "O&G",
                        "OPH",
                        "ORT",
                        "SUR")
    
    if(!(spec %in% specialty.list)){
        print("specialty not allowed")
        return(0)
    }
    
    kpi_source_helper(Mmm)
    
    path <- grep("(.*kpi.8 .*)", source.kpi$filepath, value = TRUE)
    
    DS_SDS.frame <- empty.frame
    DS_SDS.frame[1,] <- NA
    
    DS_SDS <- fuzzy_range(path, 118:220, 1:6)
    
    names(DS_SDS) <- c("cluster", "institution", "specialty", "total", "DS", "SDS")
    
    DS_SDS$institution <- gsub("^Subtotal.*", "Subtotal", DS_SDS$institution)
    
    if(spec == "Overall"){
        DS_SDS <- DS_SDS[-c(1),] %>% filter(cluster == "KW" | institution == "Subtotal" | is.na(institution))
        
        DS_SDS[nrow(DS_SDS),1] <- "HA"
        
        DS_SDS$institution <- gsub(".*total.*", NA, DS_SDS$institution)
        
        DS_SDS$cluster <- gsub(" $", "", DS_SDS$cluster)
        DS_SDS$cluster <- sapply(DS_SDS$cluster, FUN = function(x){ifelse(x=="HA", x, paste(x,"C", sep = ""))})
        
        
        for (i in 1:nrow(DS_SDS)){
            if (is.na(DS_SDS$institution[i])){
                DS_SDS$institution[i] <- DS_SDS$cluster[i]
            }
            if (is.na(DS_SDS$DS[i]) & DS_SDS$total[i]!=0){
                DS_SDS$DS[i] <- 0
            }
            if (is.na(DS_SDS$SDS[i]) & DS_SDS$total[i]!=0){
                DS_SDS$SDS[i] <- 0
            }
        }
        
        for (i in 1:3){
            for (j in 1:nrow(DS_SDS)){
                if(is.na(DS_SDS[j,i+3])){
                    DS_SDS[j,i+3] <- "0"
                }
            }
            DS_SDS[,i+3] <- as.numeric(DS_SDS[,i+3])
        }
        
        DS_SDS <- DS_SDS %>% #filter(cluster=="KWC" | cluster=="HA") %>% 
            group_by(institution) %>% summarise(SDS = sum(SDS), DS = sum(DS), total = sum(total)) %>%
            t() %>% as.data.frame(stringsAsFactors = FALSE)
        
        names(DS_SDS) <- DS_SDS[1,]
        
        DS_SDS <- DS_SDS[-1,]
        
        for (i in 1:length(DS_SDS)){
            DS_SDS[,i] <- sapply(DS_SDS[,i], FUN = function(x) as.numeric(x))
        }
        
        if(inst == "KWC"){
            DS_SDS.prod <- DS_SDS %>% select(CMC, KWH, NLTH, OLM, PMH, YCH, KWC, HA)
        }else if(inst == "HA"){
            DS_SDS.prod <- DS_SDS %>% select(HKEC, HKWC, KCC, KEC, NTEC, NTWC, KWC, HA)
        }
    
    }else{
        
        DS_SDS <- DS_SDS[-c(1),] %>% filter(specialty==spec)
        DS_SDS$cluster <- sapply(DS_SDS$cluster, FUN = function(x){ifelse(x=="HA", x, paste(x,"C", sep = ""))})
        
        for (i in 1:3){
            for (j in 1:nrow(DS_SDS)){
                if(is.na(DS_SDS[j,i+3])){
                    DS_SDS[j,i+3] <- "0"
                    }
            }
            DS_SDS[,i+3] <- as.numeric(DS_SDS[,i+3])
        }
        
        # Cluster based
        
        DS_SDS.HA <- DS_SDS %>% group_by(cluster) %>% arrange(cluster) %>% summarise(SDS = sum(SDS), DS = sum(DS), total = sum(total)) %>%
            t() %>% as.data.frame(stringsAsFactors = FALSE)
        
        names(DS_SDS.HA) <- DS_SDS.HA[1,]
        
        DS_SDS.HA <- DS_SDS.HA[-1,]
        
        for (k in 1:ncol(DS_SDS.HA)){
            DS_SDS.HA[,k] <- as.numeric(DS_SDS.HA[,k])
        }
        
        DS_SDS.HA <- DS_SDS.HA %>% mutate(KWC_ = KWC) %>% select(-KWC) %>% mutate(HA = rowSums(.))
        
        names(DS_SDS.HA)[which(names(DS_SDS.HA)=="KWC_")] <- "KWC"
        
        # Cluster based
        
        DS_SDS.KWC <- DS_SDS %>% filter(cluster=="KWC") %>% arrange(institution) %>% select(institution, SDS, DS, total) %>%
            t() %>% as.data.frame(stringsAsFactors = FALSE)
        
        names(DS_SDS.KWC) <- DS_SDS.KWC[1,]
        
        DS_SDS.KWC <- DS_SDS.KWC[-1,]
        
        for (k in 1:ncol(DS_SDS.KWC)){
            DS_SDS.KWC[,k] <- as.numeric(DS_SDS.KWC[,k])
        }
        
        h <- ncol(DS_SDS.HA)
        
        DS_SDS.KWC <- cbind(DS_SDS.KWC, DS_SDS.HA[,c(h-1,h)])
        
        names(DS_SDS.KWC)[which(names(DS_SDS.KWC)=="KWC_")] <- "KWC"
        
        if(inst=="KWC"){
            DS_SDS.prod <- DS_SDS.KWC
        }else if(inst=="HA"){
            DS_SDS.prod <- DS_SDS.HA
        }
    }
    
    # Return production dataframe
    
    DS_SDS.prod
}


# kpi.9 ALOS by specialty ------------------------------------------------

kpi.9 <- function(Mmm){
    
    kpi_source_helper(Mmm)
    
    path <- grep("(.*kpi.9 .*)", source.kpi$filepath, value = TRUE)
    
    ALOS <- read_range(path, 5:26, 1:16)
    
    for (i in 1:(ncol(ALOS)-1)){
        ALOS[,i+1] <- as.numeric(ALOS[,i+1])
    }
    
    # Check if return need to be shown by specialty and subset accordingly
    
    ALOS.frame <- ALOS
    
    ALOS.frame <- ALOS.frame[, -1]
    
    # Rounding to 1 decimal place
    
    ALOS.frame <- format(ALOS.frame, nsmall = 1)
    
    # Replace NA with "" for use in Excel
    
    if (nrow(ALOS.frame)>1){
        ALOS.prod <- data.frame(apply(ALOS.frame, 2, FUN = function(x){ifelse(grepl("NA", x), "", x)}), stringsAsFactors = FALSE)
    } else if (nrow(ALOS.frame)==1){
        ALOS.prod <- lapply(ALOS.frame, function(x){ifelse(grepl("NA", x), "", x)})
        ALOS.prod <- data.frame(ALOS.prod)
    }
    
    # Return production ready dataframe
    
    ALOS.prod
}

# kpi.3.4 & 10 Quality - Unplanned Readmission Rate within 28 days for g --------

kpi.10 <- function(Mmm, show_specialty = FALSE){
    
    kpi_source_helper(Mmm)
    
    path <- grep("(.*kpi.10 .*)", source.kpi$filepath, value = TRUE)
    
    URR <- read_range(path, 5:26, 1:15)
    
    for (i in 1:(ncol(URR)-1)){
        URR[,i+1] <- as.numeric(URR[,i+1])
    }
    
    # Check if return need to be shown by specialty and subset accordingly
    
        if (show_specialty == FALSE){
            
            URR.frame <- empty.frame
                URR.frame[1,] <- NA
            
            row.index <- 20
            URR <- URR[row.index,]
            
            for (i in 1:length(URR.frame)){
                if (names(URR.frame)[i] %in% names(URR)){
                    URR.frame[i] <- URR[names(URR.frame)[i]]
                }
            }

        } else {
            URR.frame <- URR
            URR.frame <- URR.frame[, -1]
        }
    
    # Convert to decimal percentage *(Need to consider if requried for show_specialty=TRUE)*
    if (show_specialty == FALSE){
        for (i in 1:ncol(URR.frame)){
            URR.frame[,i] <- sapply(URR.frame[,i], FUN = function(x){ifelse(is.numeric(x), x/100, x)})
        }
    }else{
        URR.frame <- format(URR.frame, nsmall = 1)
    }
    
    # Replace NA with "" for use in Excel
    
    if (nrow(URR.frame)>1){
        URR.prod <- data.frame(apply(URR.frame, 2, FUN = function(x){ifelse(grepl("NA", x), "", x)}), stringsAsFactors = FALSE)
    } else if (nrow(URR.frame)==1){
        URR.prod <- lapply(URR.frame, function(x){ifelse(is.na(x), "", x)})
        URR.prod <- data.frame(URR.prod)
    }
    
    # Return production ready dataframe
    
    URR.prod
}


# kpi.11 SOP Trend by Specialty ---------------------------------------------

kpi.11 <- function(Mmm, specialty = "Overall"){
    
    kpi_source_helper(Mmm)
    
    path <- grep("(.*kpi.11.1 .*)", source.kpi$filepath, value = TRUE)
    path.HA <- grep("(.*kpi.11.1.HA .*)", source.kpi$filepath, value = TRUE)
    
    SOP_T <- fuzzy_range(path, 5:80, 1:71)
    SOP_T.HA <- fuzzy_range(path.HA, 5:20, 1:71)
    
    # Screen TriR rows
    
    TriR <- which(SOP_T[2,] == "Tri R")
    TriR.HA <- which(SOP_T.HA[2,] == "Tri R")
    
    SOP_T.R <- SOP_T[,c(1, TriR:(TriR+11))]
    SOP_T.R.HA <- SOP_T.HA[,c(1, TriR.HA:(TriR.HA+11))]
    
    
    # Clean table
    
    names(SOP_T.R) <- SOP_T.R[3,]
    names(SOP_T.R)[1] <- "Inst"
    
    names(SOP_T.R.HA) <- SOP_T.R.HA[3,]
    names(SOP_T.R.HA)[1] <- "Specialty"
    
    
    SOP_T.R <- SOP_T.R[-(1:3),]
    SOP_T.R.HA <- SOP_T.R.HA[-(1:3),]
    
    ## Convert row lables "Overall" to "KWC"
    
    for (i in 1:nrow(SOP_T.R)){
        if(grepl("*.Overall", SOP_T.R[i,1]) & !is.na(SOP_T.R[i,2])){
            SOP_T.R[i,1] <- "KWC Mgt"
        }
    }
    
    ## Add specialty variables
    
    SOP_T.R$Specialty <- character(nrow(SOP_T.R))
    SOP_T.R$Specialty <- NA
    
    SOP_T.R.HA$Inst <- "HA"
    
    for (i in 1:nrow(SOP_T.R)){
        if(!grepl("*.Mgt$", SOP_T.R[i,1]) & is.na(SOP_T.R[i,2])){
            SOP_T.R$Specialty[i] <- SOP_T.R[i,1]
        }
    }
    
    s.index <- which(!is.na(SOP_T.R$Specialty))
    s.marker <- append(s.index, nrow(SOP_T.R)+1)
    
    for (i in 1:(length(s.marker)-1)){
        SOP_T.R$Specialty[s.marker[i]:(s.marker[i+1]-1)] <- SOP_T.R$Specialty[s.marker[i]]
    }
    
    ## Remove extra rows
    
    SOP_T.R <- SOP_T.R[-s.index,]
    
    ## Tidy up Inst names
    
    SOP_T.R$Inst <- gsub(" Mgt", "", SOP_T.R$Inst)
    SOP_T.R$Inst <- gsub("^ *", "", SOP_T.R$Inst)
    
    ## Reorder columns in HA dataframe
    
    SOP_T.R.HA <- SOP_T.R.HA[,c(14, 2:13, 1)]
    
    ## Combine dataframes
    
    SOP_T.R <- bind_rows(SOP_T.R, SOP_T.R.HA)
    
    ## Convert to numeric datatype where applicable
    
    for (i in 2:13){
        SOP_T.R[,i] <- sapply(SOP_T.R[,i], as.numeric)
    }
    
    # Filter with input criteria
    
    SOP_T.R <- SOP_T.R %>% filter(Specialty==specialty) %>% select(-Specialty)
    
    row.names(SOP_T.R) <- SOP_T.R$Inst
    
    SOP_T.R <- SOP_T.R %>% select(-Inst)
    
    SOP_T.R
    
}

kpi.11.2 <- function(Mmm){
    
    kpi_source_helper(Mmm)
    
    path <- grep("(.*kpi.11.2 .*)", source.kpi$filepath, value = TRUE)
    
    SexU_T <- fuzzy_range(path, 5:30, 1:66)
    
    # Screen TriR rows
    
    TriR <- which(SexU_T[2,] == "Tri R")

    SexU_T.R <- SexU_T[,c(1, TriR:(TriR+11))]
    
    # Clean table
    
    names(SexU_T.R) <- SexU_T.R[3,]
    names(SexU_T.R)[1] <- "Inst"
    
    SexU_T.R <- SexU_T.R[-(1:4),]
    
    # Remove extra rows
    
    SexU_T.R$Inst[which(SexU_T.R$Inst == "Overall")] <- " HA"
    SexU_T.R$Inst[which(grepl("Overall", SexU_T.R$Inst))] <- " KWC"
    
    SexU_T.R <- SexU_T.R %>% filter(grepl("^ ", SexU_T.R$Inst))
    
    ## Tidy up Inst names
    
    SexU_T.R$Inst <- gsub("^ *", "", SexU_T.R$Inst)
    
    # Remove Inst labels
    
    row.names(SexU_T.R) <- SexU_T.R$Inst
    
    SexU_T.R <- SexU_T.R %>% select(-Inst)
    
    
    ## Convert to numeric datatype where applicable
    
    for (i in 1:12){
        SexU_T.R[,i] <- sapply(SexU_T.R[,i], as.numeric)
    }
    
    # Return dataframe
    
    SexU_T.R
    
}


kpi.11.3 <- function(Mmm){
    
    kpi_source_helper(Mmm)
    
    path <- grep("(.*kpi.11.3 .*)", source.kpi$filepath, value = TRUE)
    
    UROL_T <- fuzzy_range(path, 5:30, 1:66)
    
    # Screen TriR rows
    
    TriR <- which(UROL_T[2,] == "Tri R")
    
    UROL_T.R <- UROL_T[,c(1, TriR:(TriR+11))]
    
    # Clean table
    
    names(UROL_T.R) <- UROL_T.R[3,]
    names(UROL_T.R)[1] <- "Inst"
    
    UROL_T.R <- UROL_T.R[-(1:4),]
    
    # Remove extra rows
    
    UROL_T.R$Inst[which(UROL_T.R$Inst == "Overall")] <- " HA"
    UROL_T.R$Inst[which(grepl("Overall", UROL_T.R$Inst))] <- " KWC"
    
    ## Tidy up Inst names
    
    UROL_T.R$Inst <- gsub("^ *", "", UROL_T.R$Inst)
    
    ## Convert to numeric datatype where applicable
    
    for (i in 2:13){
        UROL_T.R[,i] <- sapply(UROL_T.R[,i], as.numeric)
    }
    
    # Return dataframe
    
    row.names(UROL_T.R) <- UROL_T.R$Inst
    
    UROL_T.R <- UROL_T.R %>% select(-Inst)
    
    UROL_T.R
    
}

# tre.1 A&E Waiting Time ----------------------------------------------------

tre.1 <- function(Mmm, triage="Tri 1"){
    
    kpi_source_helper(Mmm)
    
    path <- grep("(.*tre.1 .*)", source.kpi$filepath, value = TRUE)

    AE_T <- fuzzy_range(path, 5:90, 1:14)
    
    # Name columns
    
    names(AE_T) <- AE_T[1,]
    names(AE_T)[1] <- "Inst"
    
    # Remove "Overall"
    
    AE_T <- AE_T %>% select(-Overall)
    
    # Add "Triage" variable
    
    AE_T$Triage <- character(nrow(AE_T))
    
    AE_T$Triage <- NA
    
    Tri_i <- grepl("Tri ", AE_T$Inst)
    
    for(i in 1:nrow(AE_T)){
        if(Tri_i[i]){
            AE_T$Triage[i] <- AE_T$Inst[i]
        }
    }
    
    Tri_i2 <- which(Tri_i)
    
    Tri_i2 <- append(Tri_i2, nrow(AE_T)+1)
    
    for(i in 1:(length(Tri_i2)-1)){
        AE_T$Triage[(Tri_i2[i]+1):(Tri_i2[i+1]-1)] <- AE_T$Triage[Tri_i2[i]]
    }
    
    # Drop empty rows
    
    AE_Tr <- AE_T[-c(1, which(is.na(AE_T[,2]))),]
    
    # Tidy Inst names
    
    AE_Tr$Inst <- gsub("Overall$", "HA", AE_Tr$Inst)
    AE_Tr$Inst <- gsub(".*Overall.*", "KWC", AE_Tr$Inst)
    
    # Filter Non-KWC Inst
    
    AE_Tr <- AE_Tr %>% filter(!grepl("HKEC|KCC|KEC|HKEC|HKWC|NTEC|NTWC", Inst))
    
    # Remove leading spaces
    
    AE_Tr$Inst <- gsub("^ *", "", AE_Tr$Inst)
    AE_Tr$Triage <- gsub("^ *", "", AE_Tr$Triage)
    
    # Filter according to triage input
    
    AE_Tr <- AE_Tr %>% filter(Triage==triage)
    
    # Move Inst to row names
    
    row.names(AE_Tr) <- AE_Tr$Inst
    
    # Remove excess columns
    
    AE_Tr <- AE_Tr[-c(1, 14)]
    
    ## Convert to numeric datatype where applicable
    
    for (i in 1:12){
        AE_Tr[,i] <- sapply(AE_Tr[,i], as.numeric)
        AE_Tr[,i] <- AE_Tr[,i]/100
    }
    
    # Return dataframe
    
    AE_Tr
    
}

# tre.2 SOP Waiting Time ----------------------------------------------------

# Median WT
tre.2 <- function(Mmm, triage = "Tri P1"){
    
    kpi_source_helper(Mmm)
    
    path <- grep("(.*tre.2 .*)", source.kpi$filepath, value = TRUE)
    path.HA <- grep("(.*tre.2.HA .*)", source.kpi$filepath, value = TRUE)
    
    SOP_T <- fuzzy_range(path, 5:60, 1:14)
    SOP_T.HA <- fuzzy_range(path.HA, 5:20, 1:14)
    
    # Name columns
    
    names(SOP_T) <- SOP_T[1,]
    names(SOP_T.HA) <- SOP_T.HA[1,]
    
    names(SOP_T)[1] <- "Inst"
    names(SOP_T.HA)[1] <- "Inst"
    
    # Remove "Overall"
    
    SOP_T <- SOP_T %>% select(-Overall)
    SOP_T.HA <- SOP_T.HA %>% select(-Overall)
    
    # Add "Triage" variable
    
    SOP_T$Triage <- character(nrow(SOP_T))
    SOP_T.HA$Triage <- character(nrow(SOP_T.HA))
    
    SOP_T$Triage <- NA
    SOP_T.HA$Triage <- NA
    
    Tri_i <- grepl("Tri ", SOP_T$Inst)
    Tri_i.HA <- grepl("Tri ", SOP_T.HA$Inst)
    
    for(i in 1:nrow(SOP_T)){
        if(Tri_i[i]){
            SOP_T$Triage[i] <- SOP_T$Inst[i]
        }
    }
    
    for(i in 1:nrow(SOP_T.HA)){
        if(Tri_i.HA[i]){
            SOP_T.HA$Triage[i] <- SOP_T.HA$Inst[i]
        }
    }
    
    Tri_i2 <- which(Tri_i)
    Tri_i2.HA <- which(Tri_i.HA)
    
    Tri_i2 <- append(Tri_i2, nrow(SOP_T)+1)
    Tri_i2.HA <- append(Tri_i2.HA, nrow(SOP_T.HA)+1)
    
    for(i in 1:(length(Tri_i2)-1)){
        SOP_T$Triage[(Tri_i2[i]+1):(Tri_i2[i+1]-1)] <- SOP_T$Triage[Tri_i2[i]]
    }
    
    for(i in 1:(length(Tri_i2.HA)-1)){
        SOP_T.HA$Triage[(Tri_i2.HA[i]+1):(Tri_i2.HA[i+1]-1)] <- SOP_T.HA$Triage[Tri_i2.HA[i]]
    }
    
    
    # Drop empty rows
    
    SOP_Tr <- SOP_T[-c(1, which(is.na(SOP_T[,2]))),]
    SOP_Tr.HA <- SOP_T.HA[-c(1, which(is.na(SOP_T.HA[,2]))),]
    
    # Tidy Inst names
    
    SOP_Tr$Inst <- gsub("Overall$", "KWC", SOP_Tr$Inst)
    SOP_Tr$Inst <- gsub("Mgt$", "", SOP_Tr$Inst)
    SOP_Tr$Inst <- gsub(" ", "", SOP_Tr$Inst)
    
    SOP_Tr.HA$Inst <- "HA"
    
    # Merge dataframes
    
    SOP_Tr <- bind_rows(SOP_Tr, SOP_Tr.HA)
    
    # Remove leading spaced in triage
    
    SOP_Tr$Triage <- gsub("^ *", "", SOP_Tr$Triage)
    
    # Filter according to triage input
    
    SOP_Tr <- SOP_Tr %>% filter(Triage==triage)
    
    # Move Inst to row names
    
    row.names(SOP_Tr) <- SOP_Tr$Inst
    
    # Remove excess columns
    
    SOP_Tr <- SOP_Tr %>% select(-Inst, -Triage)
    
    ## Convert to numeric datatype where applicable
    
    for (i in 1:12){
        SOP_Tr[,i] <- sapply(SOP_Tr[,i], as.numeric)
        #SOP_Tr[,i] <- sapply(SOP_Tr[,i], ceiling)
    }
    
    # Return dataframe
    
    SOP_Tr
    
}

# % seen within WT
tre.2.1 <- function(Mmm, triage = "Tri P1"){
    
    kpi_source_helper(Mmm)
    
    path <- grep("(.*tre.2.1 .*)", source.kpi$filepath, value = TRUE)
    path.HA <- grep("(.*tre.2.1.HA .*)", source.kpi$filepath, value = TRUE)
    
    SOP_T <- fuzzy_range(path, 5:25, 1:14)
    SOP_T.HA <- fuzzy_range(path.HA, 5:10, 1:14)
    
    # Name columns
    
    names(SOP_T) <- SOP_T[1,]
    names(SOP_T.HA) <- SOP_T.HA[1,]
    
    names(SOP_T)[1] <- "Inst"
    names(SOP_T.HA)[1] <- "Inst"
    
    # Remove "Overall"
    
    SOP_T <- SOP_T %>% select(-Overall)
    SOP_T.HA <- SOP_T.HA %>% select(-Overall)
    
    # Add "Triage" variable
    
    SOP_T$Triage <- character(nrow(SOP_T))
    SOP_T.HA$Triage <- character(nrow(SOP_T.HA))
    
    SOP_T$Triage <- NA
    SOP_T.HA$Triage <- NA
    
    # Test gsub
    
    SOP_T$Inst <- gsub(".*triage P1.*", "Tri P1", SOP_T$Inst)
    SOP_T$Inst <- gsub(".*triage P2.*", "Tri P2", SOP_T$Inst)
    
    SOP_T.HA$Inst <- gsub(".*triage P1.*", "Tri P1", SOP_T.HA$Inst)
    SOP_T.HA$Inst <- gsub(".*triage P2.*", "Tri P2", SOP_T.HA$Inst)
    
    
    Tri_i <- grepl("Tri ", SOP_T$Inst)
    Tri_i.HA <- grepl("Tri ", SOP_T.HA$Inst)
    
    
    for(i in 1:nrow(SOP_T)){
        if(Tri_i[i]){
            SOP_T$Triage[i] <- SOP_T$Inst[i]
        }
    }
    
    for(i in 1:nrow(SOP_T.HA)){
        if(Tri_i.HA[i]){
            SOP_T.HA$Triage[i] <- SOP_T.HA$Inst[i]
        }
    }
    
    Tri_i2 <- which(Tri_i)
    Tri_i2.HA <- which(Tri_i.HA)
    
    Tri_i2 <- append(Tri_i2, nrow(SOP_T)+1)
    Tri_i2.HA <- append(Tri_i2.HA, nrow(SOP_T.HA)+1)
    
    for(i in 1:(length(Tri_i2)-1)){
        SOP_T$Triage[(Tri_i2[i]+1):(Tri_i2[i+1]-1)] <- SOP_T$Triage[Tri_i2[i]]
    }
    
    for(i in 1:(length(Tri_i2.HA)-1)){
        SOP_T.HA$Triage[(Tri_i2.HA[i]+1):(Tri_i2.HA[i+1]-1)] <- SOP_T.HA$Triage[Tri_i2.HA[i]]
    }
    
    
    # Drop empty rows
    
    SOP_Tr <- SOP_T[-c(1, which(is.na(SOP_T[,2]))),]
    SOP_Tr.HA <- SOP_T.HA[-c(1, which(is.na(SOP_T.HA[,2]))),]
    
    # Tidy Inst names
    
    SOP_Tr$Inst <- gsub("Overall$", "KWC", SOP_Tr$Inst)
    SOP_Tr$Inst <- gsub("Mgt$", "", SOP_Tr$Inst)
    SOP_Tr$Inst <- gsub(" ", "", SOP_Tr$Inst)
    
    SOP_Tr.HA$Inst <- "HA"
    
    # Merge dataframes
    
    SOP_Tr <- bind_rows(SOP_Tr, SOP_Tr.HA)
    
    # Remove leading spaced in triage
    
    SOP_Tr$Triage <- gsub("^ *", "", SOP_Tr$Triage)
    
    # Filter according to triage input
    
    SOP_Tr <- SOP_Tr %>% filter(Triage==triage)
    
    # Move Inst to row names
    
    row.names(SOP_Tr) <- SOP_Tr$Inst
    
    # Remove excess columns
    
    SOP_Tr <- SOP_Tr %>% select(-Inst, -Triage)
    
    ## Convert to numeric datatype where applicable
    
    for (i in 1:12){
        SOP_Tr[,i] <- sapply(SOP_Tr[,i], as.numeric)
        SOP_Tr[,i] <- sapply(SOP_Tr[,i], function(x)(x/100))
    }
    
    # Return dataframe
    
    SOP_Tr
    
}



# tre.3 A&E Standardised Admission Rate ------------------------------------

tre.3 <- function(Mmm){
    
}

# tre.4 MRSA ---------------------------------------------------------------

    # C.f. kpi3.3

# tre.5 Unplanned Readmissions Rate ----------------------------------------

tre.5 <- function(Mmm){
    
}

# tre.6 Stroke --------------------------------------------------------------

tre.6 <- function(Mmm){
    
}

# tre.7 Fracture Hip -------------------------------------------------------

tre.7 <- function(Mmm){
    
}

# tre.8 Cardiac -------------------------------------------------------------

tre.8 <- function(Mmm){
    
}

# tre.9 DS +SDS ------------------------------------------------------------

tre.9 <- function(Mmm){
    
}
